[package]
name = "amm"
version = "0.1.0"
authors = ["Kyrylo Stepanov <k.stepanov@tutannota.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"
near-contract-standards = "4.0.0"
itertools = "0.10.3"